name: UV

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checlout repo 
        uses: actions/checkout@v4.2.2
      
      - name: astral-sh/setup-uv
        id: setup-uv
        uses: astral-sh/setup-uv@v4.2.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/uv.lock
            **/pyproject.toml

      - name: Install requirements
        working-directory: src/
        run: |
          uv sync --python 3.13.1
        
      - name: Run python script
        working-directory: src/
        run: |
          uv run main.py

      - name: Checking cache restore
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
                
